@node    Preface, Letter, Top, Top
@unnumbered Preface

@quotation
“that book is dead sexy” — ‘Xach on #lisp’@*
(@xref{Blurbs}.)
@end quotation

This page, and the pages it links to, contain text of the Common Lisp book Practical Common Lisp published by @uref{https://www.apress.com/us/book/9781590592397, Apress}. These pages now contain the final text as it appears in the book. If you find errors in these pages, please send email to @email{book@@gigamonkeys.com}. These pages will remain online in perpetuity -— I hope they will serve as a useful introduction to Common Lisp for folks who are curious about Lisp but maybe not yet curious enough to shell out big bucks for a dead-tree book and a good Common Lisp tutorial for folks who want to get down to real coding right away. However, don't let that stop you from buying the printed version available from Apress at your favorite local or online bookseller. For the complete bookstore browsing experience, you can read the letter to the reader (@xref{Letter}.) that appears on the back cover of the treeware edition of the book.
